# Generated by Django 4.2.16 on 2024-11-04 03:31

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="状态"
                    ),
                ),
                (
                    "del_flag",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="删除"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="编码",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="电话"
                    ),
                ),
                (
                    "gender",
                    models.PositiveIntegerField(
                        choices=[(1, "男"), (2, "女")], default=1, verbose_name="性别"
                    ),
                ),
                (
                    "nick_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="用户昵称"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("principal", "校长"),
                            ("dean", "院长"),
                            ("head", "系主任"),
                            ("counselor", "辅导员"),
                            ("homeroom", "班主任"),
                            ("teacher", "老师"),
                            ("leader", "班长"),
                            ("student", "学生"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="职位",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="image/default.png",
                        null=True,
                        upload_to="static/%Y/%m",
                        verbose_name="头像",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
                "ordering": ["-id"],
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Btn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="状态"
                    ),
                ),
                (
                    "del_flag",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="删除"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="名称",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="编码",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                ("pid", models.IntegerField(blank=True, null=True, verbose_name="父id")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "菜单"), (2, "按钮")], default=1, verbose_name="类型"
                    ),
                ),
                (
                    "perm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="权限"
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="状态"
                    ),
                ),
                (
                    "del_flag",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="删除"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="名称",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="编码",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                ("is_frame", models.BooleanField(default=False, verbose_name="外部菜单")),
                (
                    "sort",
                    models.IntegerField(blank=True, null=True, verbose_name="排序标记"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="图标"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=158, null=True, verbose_name="链接地址"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="组件"
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="users.menu",
                        verbose_name="父菜单",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="Perm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="状态"
                    ),
                ),
                (
                    "del_flag",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="删除"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="名称",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="编码",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="方法"
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "menus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perm",
                        to="users.menu",
                        verbose_name="关联菜单",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="users.perm",
                        verbose_name="父权限",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="状态"
                    ),
                ),
                (
                    "del_flag",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="删除"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="名称",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="编码",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "btns",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="users.btn",
                        verbose_name="按钮权限",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "menus",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="users.menu",
                        verbose_name="菜单权限",
                    ),
                ),
                (
                    "perms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="users.perm",
                        verbose_name="权限",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="状态"
                    ),
                ),
                (
                    "del_flag",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="删除"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="名称",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="编码",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("company", "公司"), ("department", "部门")],
                        default="company",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.dept",
                        verbose_name="上级部门",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="dept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.dept",
                verbose_name="部门",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.role", verbose_name="角色"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="update_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
