import os
import random

import django
from django.db import transaction
from django.utils import timezone
from faker import Faker

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.local")
django.setup()

from apps.users.models import Dept, Role, Menu, User

faker = Faker()


@transaction.atomic
def init_dept(dept_data):
    # 遍历每个学校，作为一级部门
    for school_name, colleges in dept_data.items():
        # print(school_name, colleges)
        school, created = Dept.objects.get_or_create(
            name=school_name, pid=None, dept_type="school", defaults={"dept_sort": 0, "sub_count": len(colleges)}
        )
        print(f"学校: {school_name}")

        # 遍历每个专业，作为二级部门
        for college_name, majors in colleges.items():
            # print(college_name, majors)
            college_dept, created = Dept.objects.get_or_create(
                name=college_name,
                dept_type="college",
                pid=school,  # 学院的 pid 是学校
                defaults={"dept_sort": 0, "sub_count": len(majors)},
            )
            print(f"  学院: {college_name}")

            # 遍历每个班级，作为三级部门
            for major_name, ids in majors.items():
                # print(class_name, ids)
                department_dept, created = Dept.objects.get_or_create(
                    name=major_name,
                    dept_type="major",
                    pid=college_dept,  # 专业的 pid 是学院
                    defaults={"dept_sort": 0, "sub_count": len(ids)},
                )
                print(f"    系部: {major_name}")

                # 遍历每个专业班级，作为四级部门
                for class_id in ids:
                    # print(class_name, class_id)
                    class_dept, created = Dept.objects.get_or_create(
                        name=class_id,
                        dept_type="class",
                        pid=department_dept,  # 班级的 pid 是专业
                        defaults={"dept_sort": 0, "sub_count": 0},  # 班级不再有子节点
                    )
                    print(f"      班级: {class_id}")


@transaction.atomic
def init_menu(menu_item, parent_menu=None):
    # 创建或更新菜单项
    menu, created = Menu.objects.update_or_create(
        id=menu_item["id"],  # 根据 ID 进行更新或创建
        defaults={
            "title": menu_item["title"],
            "name": menu_item.get("componentName"),
            "component": menu_item.get("component"),
            "menu_sort": menu_item.get("menuSort", 0),
            "icon": menu_item.get("icon"),
            "path": menu_item.get("path"),
            "i_frame": menu_item.get("iFrame", False),
            "cache": menu_item.get("cache", False),
            "hidden": menu_item.get("hidden", False),
            "permission": menu_item.get("permission"),
            "pid": parent_menu,  # 父菜单
            "sub_count": menu_item.get("subCount", 0),
            "menu_type": menu_item.get("type", 1),
        },
    )
    # 递归处理子菜单
    if "children" in menu_item:
        for child in menu_item["children"]:
            init_menu(child, menu)  # 将当前菜单作为子菜单的父级


@transaction.atomic
def init_one_menu(one_menu_data):
    pass


@transaction.atomic
def init_role(role_list):
    all_depts = Dept.objects.all()  # 获取所有部门
    all_menus = Menu.objects.all()  # 获取所有菜单

    for role_name in role_list:
        # 根据角色名称设置不同的关联逻辑 (这里是示例逻辑，可以根据需求调整)
        if role_name == "超级管理员":
            depts_to_assign = all_depts  # 超级管理员关联所有部门
            menus_to_assign = all_menus  # 超级管理员关联所有菜单
        else:
            depts_to_assign = Dept.objects.filter(name__contains=role_name.split("管理员")[0])  # 根据角色名匹配部门
            menus_to_assign = Menu.objects.filter(title__contains=role_name.split("管理员")[0])  # 根据角色名匹配菜单

        # 创建角色并关联部门和菜单
        role, created = Role.objects.get_or_create(
            name=role_name, defaults={"data_scope": "this_level", "level": 3}  # 默认数据权限和级别
        )

        # 为角色添加部门关联
        role.depts.set(depts_to_assign)

        # 为角色添加菜单关联
        role.menus.set(menus_to_assign)

        role.save()  # 保存角色


@transaction.atomic
def init_super_user():
    admin_user, created = User.objects.get_or_create(
        username="admin",
        defaults={
            "nick_name": "管理员",
            "phone": faker.phone_number()[:11],  # 生成随机11位电话号码
            "gender": 1,  # 设置性别
            "is_superuser": True,
            "is_staff": True,
            "dept": random.choice(Dept.objects.filter(del_flag=False)),  # 随机分配一个部门
            "pwd_reset_time": timezone.now(),
        },
    )
    if created:
        print("Super admin user created.")
    else:
        print("Super admin user already exists.")

    # 分配超级管理员角色
    admin_user.roles.add(Role.objects.get(name="超级管理员"))
    admin_user.set_password("123456")
    admin_user.save()


def init_user():
    # 获取角色
    principal_role = Role.objects.get(name="学校管理员")
    dean_role = Role.objects.get(name="学院管理员")
    major_role = Role.objects.get(name="专业管理员")
    counselor_role = Role.objects.get(name="班级管理员")
    student_role = Role.objects.get(name="学生")

    # 获取岗位信息
    principal_job = Job.objects.get(name="校长")
    dean_job = Job.objects.get(name="院长")
    department_head_job = Job.objects.get(name="系主任")
    counselor_job = Job.objects.get(name="辅导员")
    student_job = Job.objects.get(name="学生")

    # 获取不同级别的部门
    all_schools = Dept.objects.filter(dept_type="school")  # 学校级
    all_colleges = Dept.objects.filter(dept_type="college")  # 院级
    all_majors = Dept.objects.filter(dept_type="major")  # 系级
    all_classes = Dept.objects.filter(dept_type="class")  # 班级

    # 每个学校创建一个校长
    for school in all_schools:
        user = create_user(
            dept=school, role=principal_role, job=principal_job, nick_name="校长", username=f"principal_{school.id}"
        )
        print(f"Created Principal for {school.name}")

    # 每个学院创建一个院长
    for college in all_colleges:
        user = create_user(dept=college, role=dean_role, job=dean_job, nick_name="院长", username=f"dean_{college.id}")
        print(f"Created Dean for {college.name}")

    # 每个系创建一个系主任
    for major in all_majors:
        user = create_user(
            dept=major,
            role=major_role,
            job=department_head_job,
            nick_name="系主任",
            username=f"department_head_{major.id}",
        )
        print(f"Created Department Head for {major.name}")

    # 每个班级创建一个辅导员并创建50名学生
    for class_dept in all_classes:
        # 创建辅导员
        user = create_user(
            dept=class_dept,
            role=counselor_role,
            job=counselor_job,
            nick_name="辅导员",
            username=f"counselor_{class_dept.id}",
        )
        print(f"Created Counselor for {class_dept.name}")

        # 创建50名学生
        for _ in range(50):
            user = create_user(
                dept=class_dept,
                role=student_role,
                job=student_job,
                nick_name="学生",
                username=faker.unique.random_number(digits=8),
            )
        print(f"Created 50 Students for {class_dept.name}")


def create_user(dept, role, job, nick_name, username):
    """通用用户创建方法"""
    gender = random.choice([1, 2])  # 随机性别
    phone = "1" + faker.random_element(["3", "4", "5", "6", "7", "8", "9"]) + faker.numerify("#########")

    # 创建用户对象
    user = User(
        username=username,
        nick_name=nick_name,
        phone=phone,
        gender=gender,
        dept=dept,
        avatar_name="default_avatar.png",  # 默认头像
        pwd_reset_time=timezone.now(),
    )

    # 设置初始密码和保存用户
    user.set_password("123456")
    user.save()

    # 分配角色和岗位
    user.roles.add(role)
    user.jobs.add(job)
    user.save()

    return user


if __name__ == "__main__":
    dept_data = {
        "安徽文达信息工程学院": {
            "计算机工程学院": {
                "计算机科学与技术": ["2401", "2402", "2403", "2404", "2405"],
                "软件工程": ["2401", "2402", "2403", "2404", "2405"],
                "网络工程": ["2401", "2402", "2403", "2404", "2405"],
                "数据科学与大数据技术": ["2401", "2402", "2403", "2404", "2405"],
                "智能科学与技术": ["2401", "2402", "2403", "2404", "2405"],
                "信息安全": ["2401", "2402", "2403", "2404", "2405"],
                "数字媒体技术": ["2401", "2402", "2403", "2404", "2405"],
                "物联网工程": ["2401", "2402", "2403", "2404", "2405"],
                "虚拟现实技术": ["2401", "2402", "2403", "2404", "2405"],
            },
            "电子电气工程学院": {
                "电子信息工程": ["2401", "2402", "2403", "2404", "2405"],
                "通信工程": ["2401", "2402", "2403", "2404", "2405"],
                "自动化": ["2401", "2402", "2403", "2404", "2405"],
                "电气工程与智能控制": ["2401", "2402", "2403", "2404", "2405"],
                "电气工程及其自动化": ["2401", "2402", "2403", "2404", "2405"],
                "人工智能": ["2401", "2402", "2403", "2404", "2405"],
            },
            "会计学院": {
                "财务管理": ["2401", "2402", "2403", "2404", "2405"],
                "审计学": ["2401", "2402", "2403", "2404", "2405"],
                "会计学": ["2401", "2402", "2403", "2404", "2405"],
                "互联网金融": ["2401", "2402", "2403", "2404", "2405"],
            },
            "智能制造学院": {
                "机械设计制造及其自动化": ["2401", "2402", "2403", "2404", "2405"],
                "机械电子工程": ["2401", "2402", "2403", "2404", "2405"],
                "智能制造工程": ["2401", "2402", "2403", "2404", "2405"],
                "车辆工程": ["2401", "2402", "2403", "2404", "2405"],
                "新能源汽车工程": ["2401", "2402", "2403", "2404", "2405"],
                "工业设计": ["2401", "2402", "2403", "2404", "2405"],
                "材料成型及控制工程": ["2401", "2402", "2403", "2404", "2405"],
                "汽车服务工程": ["2401", "2402", "2403", "2404", "2405"],
                "机器人工程": ["2401", "2402", "2403", "2404", "2405"],
            },
            "艺术设计学院": {
                "动画": ["2401", "2402", "2403", "2404", "2405"],
                "视觉传达设计": ["2401", "2402", "2403", "2404", "2405"],
                "环境设计": ["2401", "2402", "2403", "2404", "2405"],
                "产品设计": ["2401", "2402", "2403", "2404", "2405"],
                "新媒体艺术": ["2401", "2402", "2403", "2404", "2405"],
            },
            "商贸学院": {
                "电子商务": ["2401", "2402", "2403", "2404", "2405"],
                "商务英语": ["2401", "2402", "2403", "2404", "2405"],
                "国际经济与贸易": ["2401", "2402", "2403", "2404", "2405"],
                "市场营销": ["2401", "2402", "2403", "2404", "2405"],
                "人力资源管理": ["2401", "2402", "2403", "2404", "2405"],
                "旅游管理与服务教育": ["2401", "2402", "2403", "2404", "2405"],
            },
            "影视传媒学院": {
                "学前教育": ["2401", "2402", "2403", "2404", "2405"],
                "播音与主持艺术": ["2401", "2402", "2403", "2404", "2405"],
                "表演专业": ["2401", "2402", "2403", "2404", "2405"],
                "广播电视编导": ["2401", "2402", "2403", "2404", "2405"],
            },
            "城市建设学院": {
                "土木工程": ["2401", "2402", "2403", "2404", "2405"],
                "风景园林": ["2401", "2402", "2403", "2404", "2405"],
                "工程管理": ["2401", "2402", "2403", "2404", "2405"],
                "工程造价": ["2401", "2402", "2403", "2404", "2405"],
            },
        }
    }
    menu_data = {
        "cache": False,
        "createTime": "2018-12-18 15:11:29",
        "hasChildren": True,
        "hidden": False,
        "iFrame": False,
        "icon": "system",
        "id": 1,
        "label": "系统管理",
        "leaf": False,
        "menuSort": 1,
        "path": "system",
        "subCount": 7,
        "title": "系统管理",
        "type": 0,
        "children": [
            {
                "cache": False,
                "component": "system/dept/index",
                "componentName": "Dept",
                "createTime": "2019-03-25 09:46:00",
                "hasChildren": True,
                "hidden": False,
                "iFrame": False,
                "icon": "dept",
                "id": 2,
                "label": "部门管理",
                "leaf": False,
                "menuSort": 6,
                "path": "dept",
                "permission": "dept:list",
                "pid": 1,
                "subCount": 3,
                "title": "部门管理",
                "type": 1,
                "children": [
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:57:09",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 9,
                        "label": "部门新增",
                        "leaf": True,
                        "menuSort": 2,
                        "path": "",
                        "permission": "dept:add",
                        "pid": 2,
                        "subCount": 0,
                        "title": "部门新增",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:57:27",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 10,
                        "label": "部门编辑",
                        "leaf": True,
                        "menuSort": 3,
                        "path": "",
                        "permission": "dept:edit",
                        "pid": 2,
                        "subCount": 0,
                        "title": "部门编辑",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:57:41",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 11,
                        "label": "部门删除",
                        "leaf": True,
                        "menuSort": 4,
                        "path": "",
                        "permission": "dept:del",
                        "pid": 2,
                        "subCount": 0,
                        "title": "部门删除",
                        "type": 2,
                    },
                ],
            },
            {
                "cache": False,
                "component": "system/role/index",
                "componentName": "Role",
                "createTime": "2018-12-18 15:16:07",
                "hasChildren": True,
                "hidden": False,
                "iFrame": False,
                "icon": "role",
                "id": 3,
                "label": "角色管理",
                "leaf": False,
                "menuSort": 3,
                "path": "role",
                "permission": "roles:list",
                "pid": 1,
                "subCount": 3,
                "title": "角色管理",
                "type": 1,
                "children": [
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:45:34",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 12,
                        "label": "角色创建",
                        "leaf": True,
                        "menuSort": 2,
                        "path": "",
                        "permission": "roles:add",
                        "pid": 3,
                        "subCount": 0,
                        "title": "角色创建",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:46:16",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 13,
                        "label": "角色修改",
                        "leaf": True,
                        "menuSort": 3,
                        "path": "",
                        "permission": "roles:edit",
                        "pid": 3,
                        "subCount": 0,
                        "title": "角色修改",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:46:51",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 14,
                        "label": "角色删除",
                        "leaf": True,
                        "menuSort": 4,
                        "path": "",
                        "permission": "roles:del",
                        "pid": 3,
                        "subCount": 0,
                        "title": "角色删除",
                        "type": 2,
                    },
                ],
            },
            {
                "cache": False,
                "component": "system/job/index",
                "componentName": "Job",
                "createTime": "2019-03-29 13:51:18",
                "hasChildren": True,
                "hidden": False,
                "iFrame": False,
                "icon": "Steve-Jobs",
                "id": 4,
                "label": "岗位管理",
                "leaf": False,
                "menuSort": 7,
                "path": "job",
                "permission": "job:list",
                "pid": 1,
                "subCount": 3,
                "title": "岗位管理",
                "type": 1,
                "children": [
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:58:27",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 15,
                        "label": "岗位新增",
                        "leaf": True,
                        "menuSort": 2,
                        "path": "",
                        "permission": "job:add",
                        "pid": 4,
                        "subCount": 0,
                        "title": "岗位新增",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:58:45",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 16,
                        "label": "岗位编辑",
                        "leaf": True,
                        "menuSort": 3,
                        "path": "",
                        "permission": "job:edit",
                        "pid": 4,
                        "subCount": 0,
                        "title": "岗位编辑",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:59:04",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 17,
                        "label": "岗位删除",
                        "leaf": True,
                        "menuSort": 4,
                        "path": "",
                        "permission": "job:del",
                        "pid": 4,
                        "subCount": 0,
                        "title": "岗位删除",
                        "type": 2,
                    },
                ],
            },
            {
                "cache": False,
                "component": "system/user/index",
                "componentName": "User",
                "createTime": "2018-12-18 15:14:44",
                "hasChildren": True,
                "hidden": False,
                "iFrame": False,
                "icon": "peoples",
                "id": 5,
                "label": "用户管理",
                "leaf": False,
                "menuSort": 2,
                "path": "user",
                "permission": "user:list",
                "pid": 1,
                "subCount": 3,
                "title": "用户管理",
                "type": 1,
                "updateBy": "admin",
                "updateTime": "2020-09-06 17:29:33",
                "children": [
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 10:59:46",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 18,
                        "label": "用户新增",
                        "leaf": True,
                        "menuSort": 2,
                        "path": "",
                        "permission": "user:add",
                        "pid": 5,
                        "subCount": 0,
                        "title": "用户新增",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 11:00:08",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 19,
                        "label": "用户编辑",
                        "leaf": True,
                        "menuSort": 3,
                        "path": "",
                        "permission": "user:edit",
                        "pid": 5,
                        "subCount": 0,
                        "title": "用户编辑",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 11:00:23",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 20,
                        "label": "用户删除",
                        "leaf": True,
                        "menuSort": 4,
                        "path": "",
                        "permission": "user:del",
                        "pid": 5,
                        "subCount": 0,
                        "title": "用户删除",
                        "type": 2,
                    },
                ],
            },
            {
                "cache": False,
                "component": "system/menu/index",
                "componentName": "Menu",
                "createTime": "2018-12-18 15:17:28",
                "hasChildren": True,
                "hidden": False,
                "iFrame": False,
                "icon": "menu",
                "id": 6,
                "label": "菜单管理",
                "leaf": False,
                "menuSort": 5,
                "path": "menu",
                "permission": "menu:list",
                "pid": 1,
                "subCount": 3,
                "title": "菜单管理",
                "type": 1,
                "children": [
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:55:07",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 21,
                        "label": "菜单新增",
                        "leaf": True,
                        "menuSort": 2,
                        "path": "",
                        "permission": "menu:add",
                        "pid": 6,
                        "subCount": 0,
                        "title": "菜单新增",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:55:40",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 22,
                        "label": "菜单编辑",
                        "leaf": True,
                        "menuSort": 3,
                        "path": "",
                        "permission": "menu:edit",
                        "pid": 6,
                        "subCount": 0,
                        "title": "菜单编辑",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 12:56:00",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 23,
                        "label": "菜单删除",
                        "leaf": True,
                        "menuSort": 4,
                        "path": "",
                        "permission": "menu:del",
                        "pid": 6,
                        "subCount": 0,
                        "title": "菜单删除",
                        "type": 2,
                    },
                ],
            },
            {
                "cache": False,
                "component": "system/dict/index",
                "componentName": "Dict",
                "createTime": "2019-04-10 11:49:04",
                "hasChildren": True,
                "hidden": False,
                "iFrame": False,
                "icon": "dictionary",
                "id": 7,
                "label": "字典管理",
                "leaf": False,
                "menuSort": 8,
                "path": "dict",
                "permission": "dict:list",
                "pid": 1,
                "subCount": 3,
                "title": "字典管理",
                "type": 1,
                "children": [
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 13:00:17",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 24,
                        "label": "字典新增",
                        "leaf": True,
                        "menuSort": 2,
                        "path": "",
                        "permission": "dict:add",
                        "pid": 7,
                        "subCount": 0,
                        "title": "字典新增",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 13:00:42",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 25,
                        "label": "字典编辑",
                        "leaf": True,
                        "menuSort": 3,
                        "path": "",
                        "permission": "dict:edit",
                        "pid": 7,
                        "subCount": 0,
                        "title": "字典编辑",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 13:00:59",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 26,
                        "label": "字典删除",
                        "leaf": True,
                        "menuSort": 4,
                        "path": "",
                        "permission": "dict:del",
                        "pid": 7,
                        "subCount": 0,
                        "title": "字典删除",
                        "type": 2,
                    },
                ],
            },
            {
                "cache": False,
                "component": "system/timing/index",
                "componentName": "Timing",
                "createTime": "2019-01-07 20:34:40",
                "hasChildren": True,
                "hidden": False,
                "iFrame": False,
                "icon": "timing",
                "id": 8,
                "label": "任务调度",
                "leaf": False,
                "menuSort": 999,
                "path": "timing",
                "permission": "timing:list",
                "pid": 1,
                "subCount": 3,
                "title": "任务调度",
                "type": 1,
                "children": [
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 13:07:28",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 27,
                        "label": "任务新增",
                        "leaf": True,
                        "menuSort": 2,
                        "path": "",
                        "permission": "timing:add",
                        "pid": 8,
                        "subCount": 0,
                        "title": "任务新增",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 13:07:41",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 28,
                        "label": "任务编辑",
                        "leaf": True,
                        "menuSort": 3,
                        "path": "",
                        "permission": "timing:edit",
                        "pid": 8,
                        "subCount": 0,
                        "title": "任务编辑",
                        "type": 2,
                    },
                    {
                        "cache": False,
                        "component": "",
                        "createTime": "2019-10-29 13:07:54",
                        "hasChildren": False,
                        "hidden": False,
                        "iFrame": False,
                        "icon": "",
                        "id": 29,
                        "label": "任务删除",
                        "leaf": True,
                        "menuSort": 4,
                        "path": "",
                        "permission": "timing:del",
                        "pid": 8,
                        "subCount": 0,
                        "title": "任务删除",
                        "type": 2,
                    },
                ],
            },
        ],
    }
    one_menu_data = [
        {
            "cache": False,
            "component": "system/dept/index",
            "componentName": "Dept",
            "createTime": "2019-03-25 09:46:00",
            "hasChildren": True,
            "hidden": False,
            "iFrame": False,
            "icon": "dept",
            "id": 2,
            "label": "部门管理",
            "leaf": False,
            "menuSort": 6,
            "path": "dept",
            "permission": "dept:list",
            "pid": 1,
            "subCount": 3,
            "title": "部门管理",
            "type": 1,
            "children": [
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:57:09",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 9,
                    "label": "部门新增",
                    "leaf": True,
                    "menuSort": 2,
                    "path": "",
                    "permission": "dept:add",
                    "pid": 2,
                    "subCount": 0,
                    "title": "部门新增",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:57:27",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 10,
                    "label": "部门编辑",
                    "leaf": True,
                    "menuSort": 3,
                    "path": "",
                    "permission": "dept:edit",
                    "pid": 2,
                    "subCount": 0,
                    "title": "部门编辑",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:57:41",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 11,
                    "label": "部门删除",
                    "leaf": True,
                    "menuSort": 4,
                    "path": "",
                    "permission": "dept:del",
                    "pid": 2,
                    "subCount": 0,
                    "title": "部门删除",
                    "type": 2,
                },
            ],
        },
        {
            "cache": False,
            "component": "system/role/index",
            "componentName": "Role",
            "createTime": "2018-12-18 15:16:07",
            "hasChildren": True,
            "hidden": False,
            "iFrame": False,
            "icon": "role",
            "id": 3,
            "label": "角色管理",
            "leaf": False,
            "menuSort": 3,
            "path": "role",
            "permission": "roles:list",
            "pid": 1,
            "subCount": 3,
            "title": "角色管理",
            "type": 1,
            "children": [
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:45:34",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 12,
                    "label": "角色创建",
                    "leaf": True,
                    "menuSort": 2,
                    "path": "",
                    "permission": "roles:add",
                    "pid": 3,
                    "subCount": 0,
                    "title": "角色创建",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:46:16",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 13,
                    "label": "角色修改",
                    "leaf": True,
                    "menuSort": 3,
                    "path": "",
                    "permission": "roles:edit",
                    "pid": 3,
                    "subCount": 0,
                    "title": "角色修改",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:46:51",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 14,
                    "label": "角色删除",
                    "leaf": True,
                    "menuSort": 4,
                    "path": "",
                    "permission": "roles:del",
                    "pid": 3,
                    "subCount": 0,
                    "title": "角色删除",
                    "type": 2,
                },
            ],
        },
        {
            "cache": False,
            "component": "system/job/index",
            "componentName": "Job",
            "createTime": "2019-03-29 13:51:18",
            "hasChildren": True,
            "hidden": False,
            "iFrame": False,
            "icon": "Steve-Jobs",
            "id": 4,
            "label": "岗位管理",
            "leaf": False,
            "menuSort": 7,
            "path": "job",
            "permission": "job:list",
            "pid": 1,
            "subCount": 3,
            "title": "岗位管理",
            "type": 1,
            "children": [
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:58:27",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 15,
                    "label": "岗位新增",
                    "leaf": True,
                    "menuSort": 2,
                    "path": "",
                    "permission": "job:add",
                    "pid": 4,
                    "subCount": 0,
                    "title": "岗位新增",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:58:45",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 16,
                    "label": "岗位编辑",
                    "leaf": True,
                    "menuSort": 3,
                    "path": "",
                    "permission": "job:edit",
                    "pid": 4,
                    "subCount": 0,
                    "title": "岗位编辑",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:59:04",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 17,
                    "label": "岗位删除",
                    "leaf": True,
                    "menuSort": 4,
                    "path": "",
                    "permission": "job:del",
                    "pid": 4,
                    "subCount": 0,
                    "title": "岗位删除",
                    "type": 2,
                },
            ],
        },
        {
            "cache": False,
            "component": "system/user/index",
            "componentName": "User",
            "createTime": "2018-12-18 15:14:44",
            "hasChildren": True,
            "hidden": False,
            "iFrame": False,
            "icon": "peoples",
            "id": 5,
            "label": "用户管理",
            "leaf": False,
            "menuSort": 2,
            "path": "user",
            "permission": "user:list",
            "pid": 1,
            "subCount": 3,
            "title": "用户管理",
            "type": 1,
            "updateBy": "admin",
            "updateTime": "2020-09-06 17:29:33",
            "children": [
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 10:59:46",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 18,
                    "label": "用户新增",
                    "leaf": True,
                    "menuSort": 2,
                    "path": "",
                    "permission": "user:add",
                    "pid": 5,
                    "subCount": 0,
                    "title": "用户新增",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 11:00:08",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 19,
                    "label": "用户编辑",
                    "leaf": True,
                    "menuSort": 3,
                    "path": "",
                    "permission": "user:edit",
                    "pid": 5,
                    "subCount": 0,
                    "title": "用户编辑",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 11:00:23",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 20,
                    "label": "用户删除",
                    "leaf": True,
                    "menuSort": 4,
                    "path": "",
                    "permission": "user:del",
                    "pid": 5,
                    "subCount": 0,
                    "title": "用户删除",
                    "type": 2,
                },
            ],
        },
        {
            "cache": False,
            "component": "system/menu/index",
            "componentName": "Menu",
            "createTime": "2018-12-18 15:17:28",
            "hasChildren": True,
            "hidden": False,
            "iFrame": False,
            "icon": "menu",
            "id": 6,
            "label": "菜单管理",
            "leaf": False,
            "menuSort": 5,
            "path": "menu",
            "permission": "menu:list",
            "pid": 1,
            "subCount": 3,
            "title": "菜单管理",
            "type": 1,
            "children": [
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:55:07",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 21,
                    "label": "菜单新增",
                    "leaf": True,
                    "menuSort": 2,
                    "path": "",
                    "permission": "menu:add",
                    "pid": 6,
                    "subCount": 0,
                    "title": "菜单新增",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:55:40",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 22,
                    "label": "菜单编辑",
                    "leaf": True,
                    "menuSort": 3,
                    "path": "",
                    "permission": "menu:edit",
                    "pid": 6,
                    "subCount": 0,
                    "title": "菜单编辑",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 12:56:00",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 23,
                    "label": "菜单删除",
                    "leaf": True,
                    "menuSort": 4,
                    "path": "",
                    "permission": "menu:del",
                    "pid": 6,
                    "subCount": 0,
                    "title": "菜单删除",
                    "type": 2,
                },
            ],
        },
        {
            "cache": False,
            "component": "system/dict/index",
            "componentName": "Dict",
            "createTime": "2019-04-10 11:49:04",
            "hasChildren": True,
            "hidden": False,
            "iFrame": False,
            "icon": "dictionary",
            "id": 7,
            "label": "字典管理",
            "leaf": False,
            "menuSort": 8,
            "path": "dict",
            "permission": "dict:list",
            "pid": 1,
            "subCount": 3,
            "title": "字典管理",
            "type": 1,
            "children": [
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:00:17",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 24,
                    "label": "字典新增",
                    "leaf": True,
                    "menuSort": 2,
                    "path": "",
                    "permission": "dict:add",
                    "pid": 7,
                    "subCount": 0,
                    "title": "字典新增",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:00:42",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 25,
                    "label": "字典编辑",
                    "leaf": True,
                    "menuSort": 3,
                    "path": "",
                    "permission": "dict:edit",
                    "pid": 7,
                    "subCount": 0,
                    "title": "字典编辑",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:00:59",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 26,
                    "label": "字典删除",
                    "leaf": True,
                    "menuSort": 4,
                    "path": "",
                    "permission": "dict:del",
                    "pid": 7,
                    "subCount": 0,
                    "title": "字典删除",
                    "type": 2,
                },
            ],
        },
        {
            "cache": False,
            "component": "system/timing/index",
            "componentName": "Timing",
            "createTime": "2019-01-07 20:34:40",
            "hasChildren": True,
            "hidden": False,
            "iFrame": False,
            "icon": "timing",
            "id": 8,
            "label": "任务调度",
            "leaf": False,
            "menuSort": 999,
            "path": "timing",
            "permission": "timing:list",
            "pid": 1,
            "subCount": 3,
            "title": "任务调度",
            "type": 1,
            "children": [
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:07:28",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 27,
                    "label": "任务新增",
                    "leaf": True,
                    "menuSort": 2,
                    "path": "",
                    "permission": "timing:add",
                    "pid": 8,
                    "subCount": 0,
                    "title": "任务新增",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:07:41",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 28,
                    "label": "任务编辑",
                    "leaf": True,
                    "menuSort": 3,
                    "path": "",
                    "permission": "timing:edit",
                    "pid": 8,
                    "subCount": 0,
                    "title": "任务编辑",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:07:54",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 29,
                    "label": "任务删除",
                    "leaf": True,
                    "menuSort": 4,
                    "path": "",
                    "permission": "timing:del",
                    "pid": 8,
                    "subCount": 0,
                    "title": "任务删除",
                    "type": 2,
                },
            ],
        },
        # TODO: Add get tasks
        {
            "cache": False,
            "component": "system/timing/index",
            "componentName": "Timing",
            "createTime": "2019-01-07 20:34:40",
            "hasChildren": True,
            "hidden": False,
            "iFrame": False,
            "icon": "timing",
            "id": 8,
            "label": "任务调度",
            "leaf": False,
            "menuSort": 999,
            "path": "timing",
            "permission": "timing:list",
            "pid": 1,
            "subCount": 3,
            "title": "任务调度",
            "type": 1,
            "children": [
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:07:28",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 27,
                    "label": "任务新增",
                    "leaf": True,
                    "menuSort": 2,
                    "path": "",
                    "permission": "timing:add",
                    "pid": 8,
                    "subCount": 0,
                    "title": "任务新增",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:07:41",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 28,
                    "label": "任务编辑",
                    "leaf": True,
                    "menuSort": 3,
                    "path": "",
                    "permission": "timing:edit",
                    "pid": 8,
                    "subCount": 0,
                    "title": "任务编辑",
                    "type": 2,
                },
                {
                    "cache": False,
                    "component": "",
                    "createTime": "2019-10-29 13:07:54",
                    "hasChildren": False,
                    "hidden": False,
                    "iFrame": False,
                    "icon": "",
                    "id": 29,
                    "label": "任务删除",
                    "leaf": True,
                    "menuSort": 4,
                    "path": "",
                    "permission": "timing:del",
                    "pid": 8,
                    "subCount": 0,
                    "title": "任务删除",
                    "type": 2,
                },
            ],
        },
    ]
    role_data = ["超级管理员", "学校管理员", "学院管理员", "系部管理员", "专业管理员", "班级管理员", "学生", "教师"]
    jobs_data = ["校长", "院长", "系主任", "辅导员", "班主任", "老师", "班长", "学生"]

    # init_dept(dept_data)
    # for menu in one_menu_data:
    #     init_menu(menu)
    # init_role(role_data)
    # init_jobs(jobs_data)
    # init_super_user()
    init_user()
